### ISSUE TITLE
Support Laravel 10

### ISSUE THREAD

**Issue by jdjd1118** [always-open/laravel-request-logger#2]
Will this package be updated to support Laravel 10?  We are trying to update our apps to use Laravel 10 and we are using your ShipEngine package.  I was going to submit a PR to support Laravel 10 in the logger but saw that composer.json supports 8.0 while Laravel 10 only supports ^8.1

Thanks!

**Comment by qschmick** [comment]
@jdjd1118 I should be able to update this soon. This package should work find in 8.1, likely just missed updating the composer.json

**Comment by qschmick** [comment]
@jdjd1118 This package should be good to support Laravel 10. Making minor updates to the ShipEngine package to also support the needed libraries.

**Comment by jdjd1118** [comment]
@qschmick Finally got around to updating to Laravel 10 but am getting these errors: 
```
Problem 1
    - always-open/laravel-process-stamps 5.x-dev requires php ^7.3 -> your php version (8.1.13) does not satisfy that requirement.
    - always-open/laravel-process-stamps v5.0.0 requires laravel/framework ^8.0|^9.0 -> found laravel/framework[v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (^10.0).
    - always-open/laravel-request-logger[v2.1.0, ..., 2.x-dev] require laravel/framework ^9.0 -> found laravel/framework[v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (^10.0).
    - always-open/shipengine v3.2.0 requires always-open/laravel-request-logger ^2.1 -> satisfiable by always-open/laravel-request-logger[v2.1.0, v2.2.0, 2.x-dev].
    - always-open/laravel-request-logger v2.2.0 requires always-open/laravel-process-stamps ^5.0 -> satisfiable by always-open/laravel-process-stamps[v5.0.0, 5.x-dev].
    - Root composer.json requires always-open/shipengine 3.2 -> satisfiable by always-open/shipengine[v3.2.0].
```

It seems like this project wasn't updated to use the updated packages for Laravel 10.

**Comment by qschmick** [comment]
@jdjd1118 There was a dep issue. Updated to use the new version of process stamps that supports laravel 10.

**Comment by jdjd1118** [comment]
Thanks!
